### ISSUE TITLE
Add cheat sheet to J topics on GitHub?

### ISSUE THREAD

**Issue by celtic-coder** [dankilman/j-cheat-sheet#1]
Hi Dan (@dankilman),

I am a newbie at the J programming language, so when you mentioned the cheat sheet on Hacker News ([https://news.ycombinator.com/item?id=21232033](https://news.ycombinator.com/item?id=21232033)), I was intrigued. I found that it is very well laid out and extremely comprehensive.

Since it is an excellent resource, perhaps you might consider adding it to the "j" and "jlang" topics on GitHub to make it more discoverable?

1. "j" - https://github.com/topics/j (66 repos)
2. "jlang" - https://github.com/topics/jlang (7 repos)

Kind Regards,
Liam

**Comment by dankilman** [comment]
Fantastic suggestion. I'm so glad you found it useful! Just added the topics to the repo
